# Site settings
title: Brandon Benefield
email: bsquared18@gmail.com
url: https://example.github.io
description:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Work/Projects settings
projectsData:
  - title: 'LimboChat'
    image: './img/limbochat.png'
    url: 'https://github.com/bbenefield89/LimboChat'
  - title: 'Random Quote Generator'
    image: './img/rqg.png'
    url: 'https://github.com/bbenefield89/RandomQuoteGenerator'

# Blog settings
blogPosts:
  - title: 'Building Your First NPM Package'
    url: 'https://medium.com/@brandonbenefield/building-your-first-npm-package-9e3c661d90c8'
  - title: 'Making Contributions To A New Code Base'
    url: 'https://medium.com/@brandonbenefield/making-contributions-to-a-new-code-base-be66d230b38e'
  - title: 'Need More Java! Pt. 1 - Data Types'
    url: 'https://medium.com/@brandonbenefield/need-more-java-3c8b457ed082'
  
# Footer settings
footer: Brandon Benefield

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/bbenefield89
  - title: github
    url: https://github.com/bbenefield89

# Build settings
markdown: kramdown
permalink: pretty
